# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170902_1021'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='asset',
            name='device_status',
            field=models.CharField(choices=[('on', '\u4e0a\u67b6'), ('on_line', '\u5728\u7ebf'), ('off_line', '\u79bb\u7ebf'), ('off', '\u4e0b\u67b6')], default='on_line', max_length=64, verbose_name='\u8d44\u4ea7\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='device_type',
            field=models.CharField(choices=[('physical_host', '\u7269\u7406\u673a'), ('virtual_host', '\u865a\u62df\u673a'), ('cloud_host', '\u4e91\u4e3b\u673a'), ('switch', '\u4ea4\u6362\u673a'), ('router', '\u8def\u7531\u5668'), ('firewall', '\u9632\u706b\u5899'), ('storage', '\u9632\u706b\u5899'), ('others', '\u5176\u4ed6')], default='virtual_host', max_length=64, verbose_name='\u8d44\u4ea7\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='repository.Tag'),
        ),
    ]
