# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20170907_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tag',
            field=models.ManyToManyField(blank=True, to='repository.Tag'),
        ),
    ]
