# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-24 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20170923_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='uuid',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='UUID'),
        ),
    ]
