# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-24 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_asset_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='\u8d44\u4ea7\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8d44\u4ea7SN\u53f7'),
        ),
    ]
