# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20170924_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=128),
        ),
    ]
